file_resolver:
  base_path: /stacks

server:
  allow_encoded_slashes: NoDecode

riiif:
  imagemagick:
    commands:
      identify: '/usr/local/bin/identify'
      convert: '/usr/local/bin/convert'

kakadu:
  enabled: false
